import {
  create,
  NButton,
  NConfigProvider,
  NLayout,
  NLayoutHeader,
  NLayoutSider,
  NLayoutContent,
  NSpace,
  NIcon,
  NDivider,
  NScrollbar,
  NH3,
  NList,
  NListItem,
  NThing,
  NEllipsis,
  NText,
  NGrid,
  NGi,
  NCard,
  NLog,
  NTimeline,
  NTimelineItem,
  NButtonGroup,
  NMessageProvider,
  NDialogProvider,
  NModal,
  NForm,
  NFormItem,
  NInput,
  NDynamicInput,
  NInputGroup,
  NCode,
  NDropdown,
} from 'naive-ui';
import hljs from 'highlight.js';

const naive = create({
  components: [
    NButton,
    NConfigProvider,
    NLayout,
    NLayoutHeader,
    NLayoutSider,
    NLayoutContent,
    NSpace,
    NIcon,
    NDivider,
    NScrollbar,
    NH3,
    NList,
    NListItem,
    NThing,
    NEllipsis,
    NText,
    NGrid,
    NGi,
    NCard,
    NLog,
    NTimeline,
    NTimelineItem,
    NButtonGroup,
    NMessageProvider,
    NDialogProvider,
    NModal,
    NForm,
    NFormItem,
    NInput,
    NDynamicInput,
    NInputGroup,
    NCode,
    NDropdown,
  ],
});

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(naive);
  hljs.configure({ ignoreUnescapedHTML: true });
  nuxtApp.vueApp.provide('hljs', hljs);
});
