/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFolderDialog: typeof import('./src/components/sidebar/dialogs/AddFolderDialog.vue')['default']
    AICollabEditDialog: typeof import('./src/components/sidebar/dialogs/AICollabEditDialog.vue')['default']
    AICollabNativeCreateDialog: typeof import('./src/components/sidebar/dialogs/AICollabNativeCreateDialog.vue')['default']
    AICollabPanelNative: typeof import('./src/components/AICollabPanelNative.vue')['default']
    AICollabTaskEditDialog: typeof import('./src/components/sidebar/dialogs/AICollabTaskEditDialog.vue')['default']
    AIToolsPanel: typeof import('./src/components/settings/AIToolsPanel.vue')['default']
    CommandIconSettings: typeof import('./src/components/CommandIconSettings.vue')['default']
    CommandPlazaDialog: typeof import('./src/components/sidebar/dialogs/CommandPlazaDialog.vue')['default']
    ConsoleArea: typeof import('./src/components/ConsoleArea.vue')['default']
    DevLogViewer: typeof import('./src/components/DevLogViewer.vue')['default']
    DualAgentCreateDialog: typeof import('./src/components/sidebar/dialogs/DualAgentCreateDialog.vue')['default']
    DualAgentPanel: typeof import('./src/components/DualAgentPanel.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    ImportTasksDialog: typeof import('./src/components/ImportTasksDialog.vue')['default']
    MCPPanel: typeof import('./src/components/settings/MCPPanel.vue')['default']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NotificationsPanel: typeof import('./src/components/NotificationsPanel.vue')['default']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    OAuthLoginDialog: typeof import('./src/components/OAuthLoginDialog.vue')['default']
    PortManagementPanel: typeof import('./src/components/PortManagementPanel.vue')['default']
    RemoteDirectoryPicker: typeof import('./src/components/sidebar/dialogs/RemoteDirectoryPicker.vue')['default']
    RenameGroupDialog: typeof import('./src/components/sidebar/dialogs/RenameGroupDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerDirectoryPicker: typeof import('./src/components/ServerDirectoryPicker.vue')['default']
    SettingsPanel: typeof import('./src/components/settings/SettingsPanel.vue')['default']
    SidebarHeader: typeof import('./src/components/sidebar/SidebarHeader.vue')['default']
    SshPanel: typeof import('./src/components/settings/SshPanel.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    TaskEditDialog: typeof import('./src/components/sidebar/dialogs/TaskEditDialog.vue')['default']
    TaskNode: typeof import('./src/components/sidebar/TaskNode.vue')['default']
    TaskSelectionDialog: typeof import('./src/components/sidebar/dialogs/TaskSelectionDialog.vue')['default']
    TaskSidebar: typeof import('./src/components/TaskSidebar.vue')['default']
    TerminalView: typeof import('./src/components/TerminalView.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    WebsitePortsPanel: typeof import('./src/components/website/WebsitePortsPanel.vue')['default']
    WebsiteSettingsPanel: typeof import('./src/components/website/WebsiteSettingsPanel.vue')['default']
    WebsiteSshPanel: typeof import('./src/components/website/WebsiteSshPanel.vue')['default']
    WelcomeScreen: typeof import('./src/components/WelcomeScreen.vue')['default']
  }
}
