/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddFolderDialog: typeof import('./src/components/sidebar/dialogs/AddFolderDialog.vue')['default']
    AgentTaskView: typeof import('./src/components/AgentTaskView.vue')['default']
    AIToolsPanel: typeof import('./src/components/settings/AIToolsPanel.vue')['default']
    BackendLogViewer: typeof import('./src/components/BackendLogViewer.vue')['default']
    CommandIconSettings: typeof import('./src/components/CommandIconSettings.vue')['default']
    CommandPlazaDialog: typeof import('./src/components/sidebar/dialogs/CommandPlazaDialog.vue')['default']
    ConsoleArea: typeof import('./src/components/ConsoleArea.vue')['default']
    IconPicker: typeof import('./src/components/IconPicker.vue')['default']
    ImportTasksDialog: typeof import('./src/components/ImportTasksDialog.vue')['default']
    MCPPanel: typeof import('./src/components/settings/MCPPanel.vue')['default']
    NAlert: typeof import('naive-ui')['NAlert']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NDynamicTags: typeof import('naive-ui')['NDynamicTags']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NList: typeof import('naive-ui')['NList']
    NListItem: typeof import('naive-ui')['NListItem']
    NModal: typeof import('naive-ui')['NModal']
    NotificationsPanel: typeof import('./src/components/NotificationsPanel.vue')['default']
    NPopover: typeof import('naive-ui')['NPopover']
    NSpace: typeof import('naive-ui')['NSpace']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    NThing: typeof import('naive-ui')['NThing']
    NTooltip: typeof import('naive-ui')['NTooltip']
    OAuthLoginDialog: typeof import('./src/components/OAuthLoginDialog.vue')['default']
    OpenClawPanel: typeof import('./src/components/settings/OpenClawPanel.vue')['default']
    PortManagementPanel: typeof import('./src/components/PortManagementPanel.vue')['default']
    RemoteDirectoryPicker: typeof import('./src/components/sidebar/dialogs/RemoteDirectoryPicker.vue')['default']
    RemoteNotificationModal: typeof import('./src/components/RemoteNotificationModal.vue')['default']
    RenameGroupDialog: typeof import('./src/components/sidebar/dialogs/RenameGroupDialog.vue')['default']
    ResumeSessionDialog: typeof import('./src/components/sidebar/dialogs/ResumeSessionDialog.vue')['default']
    RoomInfoPanel: typeof import('./src/components/RoomInfoPanel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServerDirectoryPicker: typeof import('./src/components/ServerDirectoryPicker.vue')['default']
    ServerFilePicker: typeof import('./src/components/ServerFilePicker.vue')['default']
    SettingsPanel: typeof import('./src/components/settings/SettingsPanel.vue')['default']
    SidebarHeader: typeof import('./src/components/sidebar/SidebarHeader.vue')['default']
    SshPanel: typeof import('./src/components/settings/SshPanel.vue')['default']
    StatusBar: typeof import('./src/components/StatusBar.vue')['default']
    TaskEditDialog: typeof import('./src/components/sidebar/dialogs/TaskEditDialog.vue')['default']
    TaskNode: typeof import('./src/components/sidebar/TaskNode.vue')['default']
    TaskSelectionDialog: typeof import('./src/components/sidebar/dialogs/TaskSelectionDialog.vue')['default']
    TaskSidebar: typeof import('./src/components/TaskSidebar.vue')['default']
    TerminalView: typeof import('./src/components/TerminalView.vue')['default']
    TitleBar: typeof import('./src/components/TitleBar.vue')['default']
    UserMenu: typeof import('./src/components/UserMenu.vue')['default']
    WebsitePortsPanel: typeof import('./src/components/website/WebsitePortsPanel.vue')['default']
    WebsiteSettingsPanel: typeof import('./src/components/website/WebsiteSettingsPanel.vue')['default']
    WebsiteSshPanel: typeof import('./src/components/website/WebsiteSshPanel.vue')['default']
    WelcomeScreen: typeof import('./src/components/WelcomeScreen.vue')['default']
  }
}
